
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 25 15:46:55 CEST 2016
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PARENT_CERRAR = 28;
  public static final int FUNCTION = 13;
  public static final int LITERAL_ENTERO = 2;
  public static final int CONST = 7;
  public static final int PUNTO_Y_COMA = 30;
  public static final int CIRCUNFLEJO = 37;
  public static final int INTEGER = 15;
  public static final int DOS_PUNTOS = 31;
  public static final int FOR = 12;
  public static final int WRITE = 25;
  public static final int IGUAL = 32;
  public static final int RECORD = 19;
  public static final int TYPE = 23;
  public static final int OR = 16;
  public static final int ARROBA = 38;
  public static final int PARENT_ABRIR = 27;
  public static final int BEGIN = 5;
  public static final int IF = 14;
  public static final int WRITELN = 26;
  public static final int ID = 4;
  public static final int LITERAL_CADENA = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int PROGRAM = 18;
  public static final int COMA = 29;
  public static final int MENOS = 33;
  public static final int MAYOR_QUE = 34;
  public static final int ELSE = 9;
  public static final int PUNTO = 36;
  public static final int DOS_PUNTOS_IGUAL = 35;
  public static final int TO = 21;
  public static final int THEN = 20;
  public static final int END = 10;
  public static final int FALSE = 11;
  public static final int VAR = 24;
  public static final int PROCEDURE = 17;
  public static final int DO = 8;
}

